[package]
edition = "2021"
name = "hex"
publish = false
version = "0.1.0"

[dependencies]
health = { path = "../health" }

tokio = { workspace = true, features = ["time"] }
tracing.workspace = true

[lints]
workspace = true
